# Generated by Django 2.2 on 2020-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_author_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='last_name',
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
