# Generated by Django 2.2 on 2020-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_author_app', '0002_auto_20200214_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
