# Generated by Django 2.2 on 2020-02-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_author_app', '0003_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_author_app.authors'),
            preserve_default=False,
        ),
    ]
