# Generated by Django 2.2 on 2020-02-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_author_app', '0004_books_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_author_app.authors'),
        ),
    ]
